name: avefin_lms_mobile_app
description: "Avefin mobile app"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  flutter_secure_storage: ^10.0.0
  dio: ^5.9.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
